#!/usr/bin/env python3
"""python configure.py [--version VERSION]: write build.ninja for VERSION."""
import argparse
import json
import os
import shlex
import subprocess
import sys
from urllib.parse import quote
from pathlib import Path

# (the index is VERSION in include/version.h)
VERSIONS = ["GC_1_2_5", "GC_1_2_5n", "GC_1_3", "GC_3_0a5_2"]


def pro4_arguments(args):
    """Pro 4's driver takes Microsoft-style options."""
    result, rest = [], iter(args)
    for arg in rest:
        if arg == "-o":
            result.append("/Fo" + next(rest))
        elif arg.startswith("-"):
            result.append("/" + arg[1:])
        else:
            result.append(arg)
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", choices=VERSIONS, default=VERSIONS[0])
    version = parser.parse_args().version
    config = json.loads(Path(f"config/{version}/config.json").read_text())
    sources = json.loads(Path("config/sources.json").read_text())
    # Version-specific files/settings must not enter the older versions' builds.
    sources.update(config.get("source_settings", {}))
    # An explicit source list lets a new version start with no compiled files.
    if "sources" in config:
        sources = {source: sources[source] for source in config["sources"]}
    originals = [json.loads(Path(f"config/{v}/config.json").read_text())["original"] for v in VERSIONS]
    quote_args = subprocess.list2cmdline if os.name == "nt" else shlex.join
    python = quote_args([sys.executable])
    runner = "" if os.name == "nt" else "$wibo "
    loader_dep = "" if os.name == "nt" else "$wibo "
    objdiff = "build/tools/objdiff-cli" + (".exe" if os.name == "nt" else "")
    out = [
        "# Generated by configure.py",
        f"python = {python}",
        "wibo = build/tools/wibo",
        "",
        "pool downloads",
        "  depth = 1",
        "rule download",
        "  command = $python tools/download_tool.py $tool $out",
        "  description = DOWNLOAD $out",
        "  pool = downloads",
        "rule mwcc",
        # (-MD writes <stem>.dep to the working directory)
        f"  command = $python tools/run_compiler.py --dep $stem.dep --out $out -- {runner}$compiler $cflags -MD $in -o $out",
        "  description = MWCC $in",
        "  depfile = $out.d",
        "  deps = gcc",
        "rule mwcc_pro4",
        f"  command = $python tools/run_compiler.py --out $out -- {runner}$compiler $cflags",
        "  description = MWCC $in",
        "rule extract",
        "  command = $python tools/compare.py extract $version",
        "  description = EXTRACT $version",
        "rule compare",
        "  command = $python tools/compare.py compare $version",
        "  description = COMPARE $version",
        "rule source_diff",
        "  command = $python tools/compare.py unit $version $source",
        "  description = DIFF $source",
        "rule report",
        "  command = $python tools/compare.py report $version",
        "  description = REPORT $version",
        "rule configure",
        f"  command = $python configure.py --version {version}",
        "  generator = 1",
        "",
        f"version = {version}",
        f"build {objdiff}: download",
        "  tool = objdiff-cli",
        "build build/tools/wibo: download",
        "  tool = wibo",
        f"build build/compilers/ok {' '.join(originals)}: download",
        "  tool = compilers",
    ]
    out += ["build lib/ok: download", "  tool = lib"]
    # (a version built with other compilers maps the sources' to its own: config/<version>/config.json "compilers")
    host = lambda settings: config.get("compilers", {}).get(settings["compiler"], settings["compiler"])
    for compiler in sorted({host(s) for s in sources.values()}):
        out += [f"build build/compilers/{compiler}/mwcc.exe: download", f"  tool = {compiler}"]
    objects = []
    for source, settings in sources.items():
        obj = f"build/{version}/compiled/{source}.obj"
        compiler = f"build/compilers/{host(settings)}/mwcc.exe"
        args = ["-c", *settings["flags"], f"-DVERSION={VERSIONS.index(version)}",
                *(f"-I{d}" for d in settings.get("include_dirs", [])), "-Iinclude", "-i-",
                *(f"-I{d}" for d in settings.get("system_include_dirs", [])), "-Iinclude/libc"]
        if host(settings) == "pro4":
            out += [f"build {obj}: mwcc_pro4 {source} | {loader_dep}{compiler} tools/run_compiler.py || lib/ok",
                    f"  cflags = {quote_args(pro4_arguments([*args, source, '-o', obj]))}"]
        else:
            out += [f"build {obj}: mwcc {source} | {loader_dep}{compiler} tools/run_compiler.py tools/transform_dep.py || lib/ok", f"  cflags = {quote_args(args)}",
                    f"  stem = {Path(source).stem}"]
        out.append(f"  compiler = {compiler}")
        objects.append(obj)
    configs = f"config/{version}/config.json config/{version}/functions.json config/{version}/bindings.json config/sources.json"
    target_only = []
    if config.get('translation_units'):
        configs += ' ' + config['translation_units']
        target_only = [u['source'] for u in json.loads(Path(config['translation_units']).read_text())['units']
                       if u['source'] not in sources and any(f['size'] for f in u['windows_functions'])]
    for source in [*sources, *target_only]:
        filename = quote(source, safe="/@$") + ".obj"
        target = f"build/{version}/target/{filename}".replace("$", "$$")
        base = f"build/{version}/base/{filename}".replace("$", "$$")
        outputs = target if source in target_only else f'{target} {base}'
        compiled = '' if source in target_only else f'build/{version}/compiled/{source}.obj '
        out += [f"build {outputs}: source_diff | {compiled}{config['original']} {configs} tools/compare.py tools/pe.py {objdiff}",
                f"  source = {quote_args([source]).replace('$', '$$')}"]
    out += [
        f"build build/{version}/target/ok: extract | {config['original']} {configs} tools/compare.py tools/pe.py",
        f"build build/{version}/ok objdiff.json: compare | build/{version}/target/ok {' '.join(objects)} {objdiff}",
        f"build build/{version}/report.json: report | build/{version}/ok {objdiff}",
        f"build all_source: phony {' '.join(objects)}",
        f"build progress: phony build/{version}/report.json",
        f"build build.ninja: configure | configure.py config/sources.json {' '.join(f'config/{v}/config.json' for v in VERSIONS)} {config.get('translation_units', '')}",
        f"default build/{version}/ok",
        "",
    ]
    Path("build.ninja").write_text("\n".join(out))


if __name__ == "__main__":
    main()
