#!/usr/bin/env python3
"""python configure.py [--version VERSION]: write build.ninja for VERSION."""
import argparse
import json
import shlex
import sys
from pathlib import Path

# (the index is VERSION in include/version.h)
VERSIONS = ["GC_1_2_5", "GC_1_2_5n", "GC_1_3"]


def pro4_arguments(args):
    """Pro 4's driver takes Microsoft-style options."""
    result, rest = [], iter(args)
    for arg in rest:
        if arg == "-o":
            result.append("/Fo" + next(rest))
        elif arg.startswith("-"):
            result.append("/" + arg[1:])
        else:
            result.append(arg)
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", choices=VERSIONS, default=VERSIONS[0])
    version = parser.parse_args().version
    config = json.loads(Path(f"config/{version}/config.json").read_text())
    sources = json.loads(Path("config/sources.json").read_text())
    python = shlex.quote(sys.executable)
    out = [
        "# Generated by configure.py",
        f"python = {python}",
        "wibo = build/tools/wibo",
        "",
        "pool downloads",
        "  depth = 1",
        "rule download",
        "  command = $python tools/download_tool.py $tool $out",
        "  description = DOWNLOAD $out",
        "  pool = downloads",
        "rule mwcc",
        # (-MD writes <stem>.dep to the working directory)
        "  command = MWCIncludes=include/libc $wibo $compiler $cflags -MD $in -o $out"
        " && $python tools/transform_dep.py $stem.dep $out",
        "  description = MWCC $in",
        "  depfile = $out.d",
        "  deps = gcc",
        "rule mwcc_pro4",
        "  command = MWCIncludes=include/libc $wibo $compiler $cflags",
        "  description = MWCC $in",
        "rule extract",
        "  command = $python tools/compare.py extract $version",
        "  description = EXTRACT $version",
        "rule compare",
        "  command = $python tools/compare.py compare $version",
        "  description = COMPARE $version",
        "rule report",
        "  command = $python tools/compare.py report $version",
        "  description = REPORT $version",
        "rule configure",
        f"  command = $python configure.py --version {version}",
        "  generator = 1",
        "",
        f"version = {version}",
        "build build/tools/objdiff-cli: download",
        "  tool = objdiff-cli",
        "build build/tools/wibo: download",
        "  tool = wibo",
        "build build/compilers/ok build/compilers/GC/1.2.5/mwcceppc.exe build/compilers/GC/1.2.5n/mwcceppc.exe"
        " build/compilers/GC/1.3/mwcceppc.exe: download",
        "  tool = compilers",
    ]
    out += ["build lib/ok: download", "  tool = lib"]
    # (a version built with other compilers maps the sources' to its own: config/<version>/config.json "compilers")
    host = lambda settings: config.get("compilers", {}).get(settings["compiler"], settings["compiler"])
    for compiler in sorted({host(s) for s in sources.values()}):
        out += [f"build build/compilers/{compiler}/mwcc.exe: download", f"  tool = {compiler}"]
    objects = []
    for source, settings in sources.items():
        obj = f"build/{version}/compiled/{source}.obj"
        compiler = f"build/compilers/{host(settings)}/mwcc.exe"
        args = ["-c", *settings["flags"], f"-DVERSION={VERSIONS.index(version)}",
                *(f"-I{d}" for d in settings.get("include_dirs", [])), "-Iinclude", "-i-",
                *(f"-I{d}" for d in settings.get("system_include_dirs", [])), "-Iinclude/libc"]
        if host(settings) == "pro4":
            out += [f"build {obj}: mwcc_pro4 {source} | $wibo {compiler} || lib/ok",
                    f"  cflags = {shlex.join(pro4_arguments([*args, source, '-o', obj]))}"]
        else:
            out += [f"build {obj}: mwcc {source} | $wibo {compiler} || lib/ok", f"  cflags = {shlex.join(args)}",
                    f"  stem = {Path(source).stem}"]
        out.append(f"  compiler = {compiler}")
        objects.append(obj)
    configs = f"config/{version}/config.json config/{version}/functions.json config/{version}/bindings.json config/sources.json"
    out += [
        f"build build/{version}/target/ok: extract | {config['original']} {configs} tools/compare.py tools/pe.py",
        f"build build/{version}/ok objdiff.json: compare | build/{version}/target/ok {' '.join(objects)}",
        f"build build/{version}/report.json: report | build/{version}/ok build/tools/objdiff-cli",
        f"build all_source: phony {' '.join(objects)}",
        f"build progress: phony build/{version}/report.json",
        "build build.ninja: configure | configure.py config/sources.json",
        f"default build/{version}/ok",
        "",
    ]
    Path("build.ninja").write_text("\n".join(out))


if __name__ == "__main__":
    main()
