#define ExX86_CurrentAction ExceptionX86_ExX86_CurrentAction
#define ExX86_DeletePointer ExceptionX86_ExX86_DeletePointer
#define ExX86_DeletePointerCond ExceptionX86_ExX86_DeletePointerCond
#define ExX86_DestroyLocal ExceptionX86_ExX86_DestroyLocal
#define ExX86_DestroyLocalArray ExceptionX86_ExX86_DestroyLocalArray
#define ExX86_DestroyLocalCond ExceptionX86_ExX86_DestroyLocalCond
#define ExX86_DestroyLocalPointer ExceptionX86_ExX86_DestroyLocalPointer
#define ExX86_DestroyMember ExceptionX86_ExX86_DestroyMember
#define ExX86_DestroyMemberArray ExceptionX86_ExX86_DestroyMemberArray
#define ExX86_DestroyMemberCond ExceptionX86_ExX86_DestroyMemberCond
#define ExX86_DestroyPartialArray ExceptionX86_ExX86_DestroyPartialArray
#define ExX86_FindExceptionRecord ExceptionX86_ExX86_FindExceptionRecord
#define ExX86_GetValue ExceptionX86_ExX86_GetValue
#define ExX86_HandleUnexpected ExceptionX86_ExX86_HandleUnexpected
#define ExX86_IsInSpecification ExceptionX86_ExX86_IsInSpecification
#define ExX86_LongJump ExceptionX86_ExX86_LongJump
#define ExX86_NextAction ExceptionX86_ExX86_NextAction
#define ExX86_PopStackFrame ExceptionX86_ExX86_PopStackFrame
#define ExX86_ThrowHandler ExceptionX86_ExX86_ThrowHandler
#define ExX86_UnwindStack ExceptionX86_ExX86_UnwindStack
#include "ansi_prefix.Win32.h"
#include "ExceptionX86.cpp"
